### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by tom-doerr** [avinashpaliwal/Deep-SloMo#1]
Do you already know when you will release the code?

**Comment by avinashpaliwal** [comment]
Hi @tom-doerr 
I am working on the paper submission. I will cleanup the code and should be able to push it within next two weeks.

**Comment by tom-doerr** [comment]
Okay great, thank you. :)

**Comment by jounih** [comment]
looking forward to this! Are there any limitations around resolution, video bit depth or codecs? Would 4k 10bit prores work?

**Comment by avinashpaliwal** [comment]
I have committed the test code. The limitation would be the GPU memory which would depend on the resolution of videos. A 1080 Ti with 11 GB memory would barely be able to process 1080p videos.
