### ISSUE TITLE
How to use it with regular video?

### ISSUE THREAD

**Issue by iperov** [avinashpaliwal/Deep-SloMo#2]
What is low res / hi res?

Can I just feed images from video and get x2 images output?

**Comment by avinashpaliwal** [comment]
Hi @iperov. I have added more details to the [README](https://github.com/avinashpaliwal/Deep-SloMo/blob/master/README.md) for clarification. 

This code cannot be used to upsample existing videos. It is a different application to improve the quality of slow motion videos captured using dual cameras.
