### ISSUE TITLE
High FPS videos from youtube

### ISSUE THREAD

**Issue by tlkvstepan** [avinashpaliwal/Deep-SloMo#3]
Hello Avinash,

Thank you for sharing your work.
Could you possibly also share youtube videos (or ids) that you used for training?

Best regards, Stepan

**Comment by avinashpaliwal** [comment]
Hello @tlkvstepan 

Unfortunately, I cannot publish the dataset or the IDs. I used [youtube-dl](https://ytdl-org.github.io/youtube-dl/index.html) to download N videos with search parameters for 'slow motion 240 fps' videos and 1080p/720p resolution.

Next, contiguous clips with motion were extracted from the videos.

**Comment by tlkvstepan** [comment]
Hello Avinash,
Thank you for the link!
